
-- CREATE database;

CREATE DATABASE IF NOT EXISTS northwind;

-- CREATE a user and grant privileges

CREATE USER alex;
GRANT ALL PRIVILEGES ON DATABASE northwind TO alex;
GRANT SYSTEM EXTERNALIOIMPLICITACCESS TO alex;
